# Generated by Django 4.2.7 on 2025-04-17 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL')),
                ('json_file', models.FileField(upload_to='uploads/json/', verbose_name='Archivo JSON')),
                ('browser_type', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit')], default='chromium', max_length=20, verbose_name='Tipo de navegador')),
                ('headless', models.BooleanField(default=True, verbose_name='Modo headless')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activa'), ('completed', 'Completada'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.session')),
            ],
            options={
                'verbose_name': 'Captura de pantalla',
                'verbose_name_plural': 'Capturas de pantalla',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Es válido')),
                ('data', models.JSONField(verbose_name='Datos del reporte')),
                ('html_file', models.FileField(blank=True, null=True, upload_to='reports/html/', verbose_name='Archivo HTML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='Archivo PDF')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='reports/json/', verbose_name='Archivo JSON')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/csv/', verbose_name='Archivo CSV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.session')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataLayerCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL')),
                ('data', models.JSONField(verbose_name='Datos')),
                ('is_valid', models.BooleanField(blank=True, null=True, verbose_name='Es válido')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Errores')),
                ('validated_data', models.JSONField(blank=True, null=True, verbose_name='Datos validados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalayers', to='core.session')),
            ],
            options={
                'verbose_name': 'Captura de DataLayer',
                'verbose_name_plural': 'Capturas de DataLayer',
                'ordering': ['-created_at'],
            },
        ),
    ]
