# Generated by Django 4.2.7 on 2025-04-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_session_headless'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
