# Generated by Django 4.2.7 on 2025-04-18 08:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de captura')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.session')),
            ],
            options={
                'verbose_name': 'Captura de pantalla',
                'verbose_name_plural': 'Capturas de pantalla',
                'ordering': ['-created_at'],
            },
        ),
    ]
